### PR TITLE
Adds large tests

### PR DESCRIPTION
**Pull request by IRCody**
Summary of changes:
- Adds large tests and example that runs in docker-compose/kubernetes.
- Adds README for examples/tasks and scripts.

How to verify it:
- Pull branch and run tests via commands below.

Testing done:
- make test-large
- TEST_K8s=1 make test-large

A picture of a snapping turtle (not required but encouraged):
snapping-turtle

@intelsdi-x/plugin-maintainers

### CODE REVIEW

**Comment by kindermoumoute** [comment]
You probably want #19 merged before this one, right?

**Comment by IRCody** [comment]
I guess since it seems like #19 changes the path to the binary in s3, which would require a change in this anyways.

**Comment by IRCody** [comment]
I updated with the path change from #19.

**Comment by thomastaylor312** [comment]
This tests run correctly in Jenkins as well. So this runs properly in that environment

**Pull request merged**
